# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    test:
      - step:
          name: 'Build and Push'
          script:
            - docker login $AZURE_REPOSITORY -u $AZURE_UNAME -p $AZURE_PASSWORD
            - docker build -t $AZURE_REPOSITORY/robling-dbt:latest .
            - docker push $AZURE_REPOSITORY/robling-dbt:latest
          services:
            - docker